global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'reverse-define'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics' 